site_name: Documentation - TypeGreek Windows
site_url: https://stickypiston-development.github.io/typegreek-windows/
nav:
    - 'Info':
        - 'Home': 'index.md'
        - 'Our site': 'https://stickypiston-development.github.io/typegreek-windows/'
        - 'Download latest release': 'https://github.com/StickyPiston-development/typegreek-windows/releases/latest/download/TypeGreek-installer.exe'
    - 'For users':
        - 'Installation': 'user/installation.md'
        - 'Program keybinds': 'user/keybinds.md'
        - 'Alphabet': 'user/alphabet.md'
        - 'Diacritics': 'user/diacritics.md'
        - 'Addons': 'user/addons.md'
    - 'For developers':
        - 'Contributing': 'developer/contributing.md'
        - 'Developing addons': 'developer/addons.md'
theme:
    name: material
